name: Input Credit Card No
on: 
 workflow_dispatch:
   inputs:
    cardno: 
      description: 'Enter Credit Card No'
      required: true
      default: '123456789012345'
    cardtype:
      description: 'Choose Card Type'
      required: true
      type: choice
      options:
       - master
       - visa
       - amex
      default: master 
jobs:
 validate-card:
   runs-on: ubuntu-latest 
   steps: 
     - name: check the credit card number
       run: |
          echo "Card No: ${{github.event.inputs.cardno}}"
          echo "Card Type ${{github.event.inputs.cardtype}}"
          cardNo=${{github.event.inputs.cardno}}
          echo "$cardNo"
          len=${#cardNo}
          echo "Length:$len" 
          if [ $len -lt 10 ]; then 
           echo "card no is invalid" 
          else 
           echo "card is valid" 
          fi 
  
                 
 shows-inputs:
   runs-on: ubuntu-latest
   steps:
    - name: Print the input values
      run: |
       echo "Card No: ${{github.event.inputs.cardno}}"
       echo "Card Type ${{github.event.inputs.cardtype}}"
