name: Auto Merge dev into main

on:
  workflow_dispatch:   # manually trigger
  push:
    branches:
      - feature2            # or run on dev pushes

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.GITHUBTOKENSECRET }}
         ref: main

      - name: Configure Git
        run: |
          git config user.name "eswaribala"
          git config user.email "parameswaribala@gmail.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge feature2 into main
        env:
          GH_TOKEN: ${{ secrets.GITHUBTOKENSECRET }}
        run: |
          git switch main
          git merge origin/feature2 -m "Auto-merge feature2 into master" --allow-unrelated-histories
          #git add .
          #git commit -m "updated"
          git rebase main
          git push origin main
          #git branch -d origin/feature2
          #git push origin -d origin/feature2
